# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xla_ciq_bundle.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'xla_ciq_bundle.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14xla_ciq_bundle.proto\x12\x17xla_ciq.bundle.v1alpha1\"&\n\x13\x41\x64vancedControlFile\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"\xa8\x01\n\x13\x46ingerprintMetadata\x12\x13\n\x0bkernel_name\x18\x01 \x01(\t\x12\r\n\x05shape\x18\x02 \x01(\t\x12\x0c\n\x04\x61rch\x18\x03 \x01(\t\x12\x14\n\x0c\x63uda_version\x18\x04 \x01(\t\x12\x13\n\x0b\x62\x61seline_ms\x18\x05 \x01(\x01\x12\x0f\n\x07\x62\x65st_ms\x18\x06 \x01(\x01\x12\x0f\n\x07speedup\x18\x07 \x01(\x01\x12\x12\n\nhas_timing\x18\x08 \x01(\x08\"\xf2\x04\n\x12XlaCiqTuningBundle\x12\x16\n\x0e\x66ormat_version\x18\x01 \x01(\r\x12s\n\x1e\x66ingerprint_to_control_file_id\x18\x02 \x03(\x0b\x32K.xla_ciq.bundle.v1alpha1.XlaCiqTuningBundle.FingerprintToControlFileIdEntry\x12T\n\rcontrol_files\x18\x03 \x03(\x0b\x32=.xla_ciq.bundle.v1alpha1.XlaCiqTuningBundle.ControlFilesEntry\x12g\n\x17\x66ingerprint_to_metadata\x18\x04 \x03(\x0b\x32\x46.xla_ciq.bundle.v1alpha1.XlaCiqTuningBundle.FingerprintToMetadataEntry\x1a\x41\n\x1f\x46ingerprintToControlFileIdEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x61\n\x11\x43ontrolFilesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12;\n\x05value\x18\x02 \x01(\x0b\x32,.xla_ciq.bundle.v1alpha1.AdvancedControlFile:\x02\x38\x01\x1aj\n\x1a\x46ingerprintToMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12;\n\x05value\x18\x02 \x01(\x0b\x32,.xla_ciq.bundle.v1alpha1.FingerprintMetadata:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xla_ciq_bundle_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_XLACIQTUNINGBUNDLE_FINGERPRINTTOCONTROLFILEIDENTRY']._loaded_options = None
  _globals['_XLACIQTUNINGBUNDLE_FINGERPRINTTOCONTROLFILEIDENTRY']._serialized_options = b'8\001'
  _globals['_XLACIQTUNINGBUNDLE_CONTROLFILESENTRY']._loaded_options = None
  _globals['_XLACIQTUNINGBUNDLE_CONTROLFILESENTRY']._serialized_options = b'8\001'
  _globals['_XLACIQTUNINGBUNDLE_FINGERPRINTTOMETADATAENTRY']._loaded_options = None
  _globals['_XLACIQTUNINGBUNDLE_FINGERPRINTTOMETADATAENTRY']._serialized_options = b'8\001'
  _globals['_ADVANCEDCONTROLFILE']._serialized_start=49
  _globals['_ADVANCEDCONTROLFILE']._serialized_end=87
  _globals['_FINGERPRINTMETADATA']._serialized_start=90
  _globals['_FINGERPRINTMETADATA']._serialized_end=258
  _globals['_XLACIQTUNINGBUNDLE']._serialized_start=261
  _globals['_XLACIQTUNINGBUNDLE']._serialized_end=887
  _globals['_XLACIQTUNINGBUNDLE_FINGERPRINTTOCONTROLFILEIDENTRY']._serialized_start=615
  _globals['_XLACIQTUNINGBUNDLE_FINGERPRINTTOCONTROLFILEIDENTRY']._serialized_end=680
  _globals['_XLACIQTUNINGBUNDLE_CONTROLFILESENTRY']._serialized_start=682
  _globals['_XLACIQTUNINGBUNDLE_CONTROLFILESENTRY']._serialized_end=779
  _globals['_XLACIQTUNINGBUNDLE_FINGERPRINTTOMETADATAENTRY']._serialized_start=781
  _globals['_XLACIQTUNINGBUNDLE_FINGERPRINTTOMETADATAENTRY']._serialized_end=887
# @@protoc_insertion_point(module_scope)
